### PR TITLE
Add the possibility to use weakify with returning method

### PR DESCRIPTION
**Pull request by zarghol**
Possibility now to use a default value to use when strongSelf couldn't be computed

### CODE REVIEW

**Comment by vincent-pradeilles** [comment]
I see you've removed the `public` access, can confirm that the methods are still accessible from outside the framework?

**Comment by zarghol** [comment]
Yes, I had a warning from Xcode because redundancy : The extension is public so all methods inside are too

**Comment by zarghol** [comment]
Is it okay for you ?

**Comment by vincent-pradeilles** [comment]
Good for me! I'll update the README and make a proper release in the coming days. Thanks for contributing!

**Pull request merged**
